# ZEPSUTY #2
- name: Sprawdź miejsce na dysku
  hosts: all
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python

  tasks:
    - name: Ile wolnego
      ansible.builtin.command: df -h /
      register: df
      changed_when: false

    - name: Pokaż
      ansible.builtin.debug:
        var: df.stdout_lines
